### ISSUE TITLE
DNS over HTTPS

### ISSUE THREAD

**Issue by croulibri** [YunoHost-Apps/adguardhome_ynh#10]
Hello,

I have adguard version: v0.102.0 install through Yunohost on a specific subdomain where only adguard is installed adg.mydomain.com

When I want to activate https, I have the following message : "_Error: control/tls/validate | port 443 is not available, cannot enable HTTPS on it | 400_"

I have other subdomain on my Yunohost server with other apps, some of them using port 443 on their subdomain.
But no other apps are present in adg.mydomain.com subdomain so 443 is available on that subdomain.

Is there a way to use DoH with address like https://adg.mydomain.com/dns-query ?

Thanks in advance for your advices

**Comment by liberodark** [comment]
Have possibility to use DOH with Cloudflare.

**Comment by croulibri** [comment]
This means that for the moment we can't use DoH with address like https://adg.mydomain.com/dns-query directly without using an intermediary like Cloudfare?

**Comment by dumprop** [comment]
![image](https://user-images.githubusercontent.com/34004367/135673282-3d72e6dd-4cc0-45eb-b168-ebda271bfc2a.png)
There need some encryption tweaks 
Also I too need DoH out of the box

**Comment by dumprop** [comment]
> 
> 
> This means that for the moment we can't use DoH with address like https://adg.mydomain.com/dns-query directly without using an intermediary like Cloudfare?

You will use Cloudfare DoH then :)

**Comment by xplosionmind** [comment]
<img width="374" alt="Screenshot 2021-11-23 at 9 44 33 AM" src="https://user-images.githubusercontent.com/42862428/142993793-a85daac8-014b-42b8-b12b-8d0e86894eb4.png">

The error is still appearing. Any ETA for a fix? Or is it an upstream issue?

**Comment by dumprop** [comment]
> <img alt="Screenshot 2021-11-23 at 9 44 33 AM" width="374" src="https://user-images.githubusercontent.com/42862428/142993793-a85daac8-014b-42b8-b12b-8d0e86894eb4.png">
> 
> The error is still appearing. Any ETA for a fix? Or is it an upstream issue?

No, its YNH package issue

**Comment by kay0u** [comment]
I spent some time trying to fix it, without success. A PR is welcome if someone can get the DoH to work

**Comment by kay0u** [comment]
#33 should fix this! Feedback are welcome :+1:
