### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by eldertek** [YunoHost-Apps/adguardhome_ynh#108]
### Describe the bug
The DNS configuration of my yunohost server is currently corrupted, which allows criminals to use my server for DNS amplification attacks. (Mail received from my Hosting)

### Context
Hardware: VPS bought online
YunoHost version: 11.1.20
I have access to my server: Through SSH and Web Admin
Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: No

### Steps to reproduce
Just install Adguard Home.

### Expected behavior
Server should not be used in DNS amplification attacks.

### Logs
No logs.

**Comment by tibs245** [comment]
Hi,

Have you tried enabling a DNS block list to prevent your DNS server from being used for this purpose?

**Comment by eldertek** [comment]
Right ! Thanks
