### ISSUE TITLE
Question: How does this interfere with dnsmasq?

### ISSUE THREAD

**Issue by h3ndrik** [YunoHost-Apps/adguardhome_ynh#113]
I'm missing some documentation here:

How does adguardhome_ynh (or pihole) interfere with dnsmasq?
Currently my YuhoHost has `dnsmasq` listening on 0.0.0.0:53 and [::]:53
Also dnsmasq has a custom and YunoHost-specific configuration.

Is this disabled/overwritten? Does adguard only server external requests? Or does my mailserver inside YunoHost do dns queries through adguardhome from then on?

**Comment by OniriCorpe** [comment]
I had to do research for this: https://github.com/YunoHost-Apps/adguardhome_ynh/pull/154#issuecomment-1869889497

in the case of an AGH installation:
> dnsmasq uses port 53 on localhost
> and AGH uses port 53 on outsides IP (local or public ones if needed)

so dnsmasq is left alone to live its life, in parallel of AGH
so it is not disabled nor overwritten for the localhost use
but for the outside world (the domestic network of the user or Internet if exposed to), it's AGH who responds to DNS requests

> Does adguard only server external requests?
So: yes

> Or does my mailserver inside YunoHost do dns queries through adguardhome from then on?
So: no, as the mailserver probably asks to localhost:53

have I replied to all of your questions? can I close this issue?

**Comment by h3ndrik** [comment]
Thank you very much
