### ISSUE TITLE
AGH uses port 54 because port 53 already used

### ISSUE THREAD

**Issue by gwlegion** [YunoHost-Apps/adguardhome_ynh#155]
hi.

i got ynh on a rpi 3B+ everithing upated
with the last update, i've got a bug ... with high CPU usage and high upload usage.
got to reinstall adguard, but it's configured on port 54 instead of 53 ... and i don't know how to configure it

**Comment by OniriCorpe** [comment]
For the high CPU and upload consumption, I don't know

But the port 53 config will be supported when I'll finish my work on #153 
No ETA for now, it's a non trivial modification of the package:/

**Comment by OniriCorpe** [comment]
You can fix manually this bug using:

`yunohost app setting adguardhome port_adguard`
To validate that the current configured port in the package is the 54

Then 
`yunohost app setting adguardhome port_adguard --value 53`
To set it to 53

And finally 
`yunohost app upgrade adguardhome --force`
To properly regenerate the config file

**Comment by gwlegion** [comment]
instant full cpu and upload usage when i config to port 53 . 
maybe some conflict with dnsmasq ?

**Comment by OniriCorpe** [comment]
> maybe some conflict with dnsmasq ?

it should not, see: https://github.com/YunoHost-Apps/adguardhome_ynh/issues/113#issuecomment-1869907129 😕

**Comment by Splarkszter** [comment]
> You can fix manually this bug using:

Thanks this finally solved my issue.

No device will change ports for seeking DNS queries so this is a very critical issue.

**Comment by OniriCorpe** [comment]
> No device will change ports for seeking DNS queries so this is a very critical issue.

Yes I know
I do my best

**Comment by Splarkszter** [comment]
> Yes I know I do my best

Thanks. I'm sorry if i sounded too harsh, I need to remember myself this is all voluntary work and I thank you a lot for this.
I'm sorry I present some harshness because I'm constantly fighting against the dystopia, I need to touch my hearth more often.

Thank you a lot for the work you do, thank you for making the world a better place :)

**Comment by gwlegion** [comment]
i've uninstalled adguard home ... 
still have warning about port 53 not reachable from internet ... 
think i got two bad un installations on my system ... may you help me ?

**Comment by Splarkszter** [comment]
> still have warning about port 53 not reachable from internet


If you only use yunohost for hosting on your local home network only you don;t have to wory about that.

**Comment by gwlegion** [comment]
the problem is that AGH doesn't uninstall correctly ...

**Comment by OniriCorpe** [comment]
It will be fixed when I'll finish my work on https://github.com/YunoHost-Apps/adguardhome_ynh/pull/154 
please be patient

**Comment by OniriCorpe** [comment]
should be fied with `0.107.44~ynh2`
