### ISSUE TITLE
Cannot access Adguard after install

### ISSUE THREAD

**Issue by rekesz4** [YunoHost-Apps/adguardhome_ynh#16]
Hi,

I've installed Adguard using the admin 3rd party install tool and using ssh as well, but I cannot get it to work. When I used the former I got a 404 when I accessed it (example.com/adguard) and now I get a Forbidden message (example.com/ad). I tried installing net-tools, but they are already up to date, systemctl shows that adguard is loaded and grep 53 seems to show something. If I can provide anything else to help please let me know.

**Comment by gabelluardo** [comment]
I had the same problem, you have to install it in the root path of a new domain

**Comment by kay0u** [comment]
Should be fixed now
