### ISSUE TITLE
Changing URL does not change all permissions

### ISSUE THREAD

**Issue by tituspijean** [YunoHost-Apps/adguardhome_ynh#161]
### Describe the bug

The regex permissions (api and doh) are unchanged after changing URL:

![image](https://github.com/YunoHost-Apps/adguardhome_ynh/assets/8769166/4e8194fe-334d-4100-a1ca-fffa8da14e76)

### Context

- Using, or trying to install package version/branch: 0.107.44~ynh3

**Comment by OniriCorpe** [comment]
cf https://github.com/YunoHost/issues/issues/2294
