### ISSUE TITLE
port 853 in use while upgrading despite all actions

### ISSUE THREAD

**Issue by gcollin** [YunoHost-Apps/adguardhome_ynh#183]
### Describe the bug

Error "Failed to update Ports : Port 853 is already in use by another app"  while upgrading the Application.

### Context

- Hardware: *VPS bought online*
- YunoHost version:11.2.15
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: 0.107.51-ynh1
- If upgrading, current package version: *0.107.48~ynh2`*
- Is DNS over HTTP or DNS over QUIC activated?: *no*, but I may have done it before

### Steps to reproduce
- Rebooted the server
- Checked that DNS over HTTP is disabled both in Adguard and in Yunohost admin console
- Ran twice the firewall scripts:
```
yunohost firewall disallow Both 853 --no-reload && yunohost firewall disallow Both 784
Warning: Port 853 is already closed for IPv4 connections
Warning: Port 853 is already closed for IPv6 connections
Warning: Port 853 is already closed for IPv4 connections
Warning: Port 853 is already closed for IPv6 connections
Warning: Port 784 is already closed for IPv4 connections
Warning: Port 784 is already closed for IPv6 connections
Warning: Port 784 is already closed for IPv4 connections
Warning: Port 784 is already closed for IPv6 connections
Success! Firewall reloaded
opened_ports:
- 22
- 25
- 53
- 80
- 443
- 587
- 993
- 5222
- 5269
- 5353

```
- Just accept the upgrade proposal in the webadmin
- See the error Port 853 already in use.

### Expected behavior

As port is disabled, no applications should already use it, hence upgrade should not failed.

### Logs

Please see https://paste.yunohost.org/raw/sigirefune

**Comment by FranzMari** [comment]
It is a Yunohost issue, check [here](https://github.com/YunoHost/issues/issues/2404) for context and possible solutions

**Comment by gcollin** [comment]
I applied the fix provided here: https://github.com/YunoHost/issues/issues/2404#issuecomment-2177210223, and I could install the new version without problems.
Thanks for the support
