### ISSUE TITLE
Nothing is logged, no stat shown

### ISSUE THREAD

**Issue by Enthouane** [YunoHost-Apps/adguardhome_ynh#20]
I can tell that the blocking works (tried a few of the first blacklisted domains) and DNS stalls, as should. 
But nothing is shown in the admin panel : no client, no query, nothing

![image](https://user-images.githubusercontent.com/94701334/142652296-6753e8c7-7931-4c74-bc4f-b30f4d5e2ecd.png)

**Comment by Enthouane** [comment]
Some more testing showed that it does in fact not work at all.

**Comment by Bennneeeet** [comment]
Can confirm that. I've the same issue on a fresh Yunohost install. 
If I change the DNS entries of my devices (for testing, not the whole router), then there is no connection to the internet, nothing logged.

Can anyone help?

**Comment by kay0u** [comment]
Should be fixed by #30
