### ISSUE TITLE
Change app url operation fails for adguard ynh

### ISSUE THREAD

**Issue by lightnin** [YunoHost-Apps/adguardhome_ynh#28]
### Describe the bug

Attempt to change app url in app settings admin dialog fails.

### Context
Rpi4 
Yunohost 4.3.5
Adguard version 0.107.0~ynh1

### Steps to reproduce

Install adguard home in Yunohost. Specify default installation url / domain.
Enter app properties after successful install.
In "Change the access URL of this application (domain and/or path)." field, add a folder under the same domain. (i.e. adguard)
Upgrade fails and app is restored to previous state.

### Expected behavior
URL is changed successfully. 

### Logs

 https://paste.yunohost.org/raw/qirezexidu

**Comment by kay0u** [comment]
> You must use a root domain

You can't use the path `/adguard` for this app, but you can create the domain `adguard.domain.tld/` and dedicate it to adguard

**Comment by lightnin** [comment]
So should the field that purports to allow the admin to add a subfolder path be removed?

**Comment by kay0u** [comment]
#33 should fix this, after merging it, we can install adguard on a subpath url
