### ISSUE TITLE
Required router DNS settings unclear due to use of non-standard DNS port

### ISSUE THREAD

**Issue by lightnin** [YunoHost-Apps/adguardhome_ynh#29]
It's unclear what the user needs to do to successfully configure this app given that the required port used by adguard on yunohost is not the standard DNS port. I'm sure there is a good reason for this, but it creates a need to workaround / solve this with documentation / readme.

### Context
After installation, Adguard offers a setup instruction that indicates that the user's router static DNS should be configured to: [yunohost IP address]:54 to enable blocking of ad based network traffic.

This requires specifying a non-standard DNS port (54) in the static DNS field of the user's router to successfully configure adguard. Many user's router firmware may not offer this as an easily configurable option. I use DD-WRT, which - surprisingly - doesn't allow specifying ports for the DNS in the router's software.  After several searches for a solution I was unable to find one.

Assuming there is no way to enable adguard to use port 53, removing the need to specify a non-standard port in the router firmware settings, we should explore how to help the user setup an alternative configuration.

**Comment by kay0u** [comment]
That's right! Yunohost uses dnsmasq on port 53, but only for localhost addresses.
AdguardHome listens by default on all addresses (0.0.0.0) that's why we decided to change the port, without really knowing that it was very complicated for the users to change this dns port. A simple solution is to listen only on private addresses, should be fixed by #30

**Comment by lightnin** [comment]
Ah - great that you have a solution to this issue. One thing that isn't clear to me though: "A simple solution is to listen only on private addresses"  What exactly will be the required router configuration for static DNS to use adguard after this change?

**Comment by kay0u** [comment]
In your router, you just have to set the IP of your server as the DNS server (and you can keep your router as the 2nd DNS server if needed), everything should be fine

**Comment by lightnin** [comment]
That should be perfect from a UX / setup perspective - pretty easy and intuitive.  I'm looking forward to testing it out!

**Comment by kay0u** [comment]
The package should be available in next few hours, I'm waiting for your feedback :smiley:
