### ISSUE TITLE
Installation fails 0.107.2~ynh1 on ynh 4.3.5 "error: An error occurred inside the app installation script"

### ISSUE THREAD

**Issue by lightnin** [YunoHost-Apps/adguardhome_ynh#32]
Attempted to install 0.107.2~ynh1.
Option "Should this app be exposed to anonymous visitors?" set to false

Installation log:
https://paste.yunohost.org/raw/tagosudeta

**Comment by kay0u** [comment]
Thanks for the feedback, #33 should fix this issue, I'm waiting for the package_check before merging it

**Comment by lightnin** [comment]
On a related note, it looks like the log linked above shows the unhashed admin password requested in the install step. That seems not-so-great in case, for example, the installing user likes to use the same password for multiple things and doesn't follow good password practices. 
I'm not sure if that's a standard practice in app installs that have to have their own admin passwords (instead of using privs from the LDAP'd admin yunohost user, which I'd guess is preferable when possible), or if it's just this app doing it. So I'm not sure where to file the bug - any suggestions?

**Comment by kay0u** [comment]
There is a bug in the share logs of YunoHost, good catch!

**Comment by lightnin** [comment]
Great - do I need to file it somewhere, or will you take it from here @kay0u ?

**Comment by kay0u** [comment]
We are working on it :)
