### ISSUE TITLE
Unable to install adguardhome: An error occurred

### ISSUE THREAD

**Issue by iamregve** [YunoHost-Apps/adguardhome_ynh#34]
First of all, thank you so much for maintaining this for Yunohost! 👍 

I've been dabbling with other alternatives to yunohost lately. Coming back to yunohost todayt, the install of Adguard Home failed.

### Describe the bug

Adguard Home failed to install. Both using webadmin, as well as terminal (stable and testing tree)

### Context

- Hardware: Raspberry Pi 4 at home
- ARM64 Debian 11 (raspberry os arm64)
- YunoHost version: 11.0.1~alpha+202201111617 (unstable)
- I have access to my server: Through SSH and through the webadmin
- Trying to install package version/branch: Adguard Home 0.107.2~ynh2 as well as the testing branch

### Steps to reproduce

- Installing through the webadmin
- or
- sudo yunohost app install https://github.com/YunoHost-Apps/adguardhome_ynh/tree/testing --debug

### Expected behavior

Successful installation.

### Logs

This log is from the testing tree installed with the terminal through ssh.

https://paste.yunohost.org/raw/jevifeyuqu

Thanks!

**Comment by kay0u** [comment]
Thanks for the report, can you try to install the latest testing version
```
sudo yunohost app install https://github.com/YunoHost-Apps/adguardhome_ynh/tree/testing --debug
```

Tell me if it works on your side so that I can merge the PR

**Comment by iamregve** [comment]
Hi, thank for the quick reply.

Just tried installing the latest testing version and the install did not complete:

https://paste.yunohost.org/raw/tusohonoqi

**Comment by kay0u** [comment]
> Job for dnsmasq.service failed because the control process exited with error code.
See "systemctl status dnsmasq.service" and "journalctl -xe" for details.

Can I get the logs from these commands please?

**Comment by iamregve** [comment]
Yeah, I actually noticed something iffy about dnsmasq during the install of Adguard. Checking the logs, I saw that dnsmasq was trying to find wlan0, which is disabled on my raspberry. It seemed like dnsmasq shutdown because it couldn't find the wlan, or something like that.

I managed to get dnsmasq running again and left it at that last night. As it was running as normal I wanted to try installing Adguard again just now, and check how dnsmasq reacted, but the install worked! Not sure if you changed something with the testing version but now Adguard seems to be working perfectly. I attached the install log :)

[20220113-181541-app_install-adguardhome.log](https://github.com/YunoHost-Apps/adguardhome_ynh/files/7865179/20220113-181541-app_install-adguardhome.log)

**Comment by kay0u** [comment]
No I didn't changed anything in the testing version.

I think it's a bug introduced in YunoHost 4.3.4, related to [this commit](https://github.com/YunoHost/yunohost/commit/7e7dbe41d711462d6db746e4d0dd4a44ad4c4b2e#diff-1ec676fcd363825d1eb2b5018dda03c35b65c7f511bc3dc092d3e7245ec42d83) where we now make dnsmasq listen on all wireless interfaces. We should check that the interface is up during dnsmasq regen conf.

Can you confirm that you have disabled your wlan0 interface again after formatting your SD card? Can you also confirm, with wlan0 disabled you still have the file `/sys/class/net/wlan0/wireless`?

I'll try to dig this dnsmasq issue, but from what I understand it's not really a bug in `adguardhome_ynh` package.

**Comment by iamregve** [comment]
Ahh I see. Thanks a lot for your help in this! :)

Running ifconfig only gives me eth0 and lo.

To disable wifi I did two things:
- added "dtoverlay=disable-wifi" to /boot/config.txt
- added "blacklist brcmfmac" and "blacklist brcmutil" to /etc/modprobe.d/raspi-blacklist.conf

The result of running "cat /sys/class/net/wlan0/operstate":

> pi@yuno:~ $ sudo cat /sys/class/net/wlan0/operstate                                                                                                                                           
> down

**Comment by kay0u** [comment]
Ok, so [this fix] should(https://github.com/YunoHost/yunohost/pull/1410) do the trick. If you want a workaround, you can edit the file `/etc/dnsmasq.conf` and remove `wlan0` form the `interface` field, then restart dnsmasq with `systemctl restart dnsmasq`.

But if you do that, once the patch is in production, you'll have to manually run the regen-conf with `sudo yunohost tools regen-conf dnsmasq -f`

**Comment by iamregve** [comment]
yes, think so :)

The work around is working perfectly. Tried it on the current yunohost install, as well as a reformat/reinstall, and everything is fine and dandy!

Thank you so much for all the help and you must have a great weekend! :D

**Comment by kay0u** [comment]
Thank you for reporting this problem, it helps a lot to fix some small bugs that are annoying for users.

Have a great weekend too!
