### ISSUE TITLE
Not possible to install on base domain url

### ISSUE THREAD

**Issue by lightnin** [YunoHost-Apps/adguardhome_ynh#36]
The install dialog requires that the user enter a subfolder path on the selected domain. This shouldn't be required if the domain has no other app on it. 

(Great job btw - seems to be working great other than this minor issue!)

**Comment by kay0u** [comment]
You can just enter `/`, right? Or am I missing something here?

**Comment by lightnin** [comment]
I didn't try that - I was confused as to why it wouldn't accept no characters / input of any kind as an argument, given that I wanted to install at the root of a subdomain. Seems like it should accept no input, right?

**Comment by kay0u** [comment]
As any other apps, it doesn't accept no input, it accept: `/` for the root domain, and `/foobar` for a subpath

**Comment by lightnin** [comment]
I see. I think it's strange to require "/" as an input, but perhaps there is some thinking behind it that I haven't considered. 

To me the behavior should be:
- If no input in path field, check to see if another app is already installed at root of the subdomain.
   Yes? Throw error message. "Another app is installed at the root of this subdomain. Select a different subdomain or indicate a subpath."
  No ? Install the app at the subdomain's root.

Requiring the user to enter '/' seems potentially confusing for users who aren't tech savvy. 
I'll close this since it's not an issue related directly to adguard - which is working fantastically for me for the past week, btw. Thanks again for all your efforts, @kay0u

**Comment by kay0u** [comment]
For me, forcing the `/` value for root installation is also a safeguard to prevent uninitiated people from installing an app in the root by mistake, but it may be confusing.

I don't have a strong opinion on it, but I guess you can open an issue on [Yunohost/issue](https://github.com/YunoHost/issues/) if you want.

You're welcome, glad to hear it's working well :+1:
