### ISSUE TITLE
Crash if the server doesn't have IPv6

### ISSUE THREAD

**Issue by addictif80** [YunoHost-Apps/adguardhome_ynh#41]
### Describe the bug

Fresh YunoHost install on Debian 10 VPS
main domain at ynh.domain.tld
SSL certificat created
AdGuard installed at ynh.domain.tld/adguard

### Context

- Hardware: *VPS bought online*
- YunoHost version: 4.3.6.2
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### Steps to reproduce
install AdGuard app to ynh.domain.tld/adguard
visit ynh.domain.tld/adguard
showing 502 error bad gateway

**Comment by kay0u** [comment]
Hello!

May I have logs from the service `adguardhome` please? (Using the yunohost admin ->  Services -> Adguardhome -> Share logs)

**Comment by addictif80** [comment]
Sorry, i've sent this issue at work with my smartphone and forgive to attach the log link
https://paste.yunohost.org/paxefiyihe

**Comment by kay0u** [comment]
Can I get logs of the install script please?

**Comment by addictif80** [comment]
There is my installation log : [https://pastebin.com/etfPi4Nx](https://pastebin.com/etfPi4Nx)
In this log, there are the changed values : 

- IPV6 address (my-ipv6)
- username (my-username)
- password  (**************************)

**Comment by kay0u** [comment]
Thank you for the logs.

I don't understand why you have the error
```
couldn't start forwarding DNS server: listening to udp socket: listen udp [IPV6]:53: bind: invalid argument
```
more precisely, what is this `IPV6`, it should be your ipv6 (the value of `my-ipv6` in your install logs), same for IPV4

**Comment by addictif80** [comment]
Thanks for your reply.
On my VPS (iOnos), i haven't attributed IPV6 address. I juste have created an IPV6 address and set the reverse proxy, and i will try to reinstall AdGuard.
On my Synology, i do not have an IPV6 address and work properly.

**Comment by kay0u** [comment]
> after having created an IPV6 on iOnos for my VPS, reboot VPS and reinstalling AdGuard, the adguard service successfully started and error 502 is finish.
I will try to configure AdGuard and use it with my computer for testing.
>
> Do you know if i need to configure my DNS area with AAAA record ?

That's a bug, because if you don't have an ipv6, the script install should detect it and shouldn't enable it on adguard.

>  In encryption setting, i have this error, but 443 is open in firewall and used domain have a SSL certificate (not self signed)

It's for DNS over HTTPS, it works correctly even with this error message: https://github.com/YunoHost-Apps/adguardhome_ynh/issues/10#issuecomment-1007262989

**Comment by addictif80** [comment]
Thank you for your quick help.
You're awesome !
I close this issue :)

For resume : 
AdGuard need an IPV6 address and it work properly :)

**Comment by kay0u** [comment]
I'm not saying that, IPV6 is not mandatory, it's a bug I'm trying to address :)

**Comment by addictif80** [comment]
Oh ok, sorry for closing this issue :p 
Since my latest post, AdGuard Home work properly, but i don't know what i need to configure.
And, on Youtube, many videos has blocked, with message "contact your network administrator"

**Comment by Viguro79** [comment]
Hi.
Same issue here after upgrading to the newest AdGuard Home, version v0.107.8.
After update, I got a "502 bad gateway" issue.
```
Jul 23 18:19:32 AdGuardHome[2944]: 2022/07/23 18:19:32.277463 [info] Listening to udp://192.168.1.10:53
Jul 23 18:19:32 AdGuardHome[2944]: 2022/07/23 18:19:32.277490 [info] Creating the UDP server socket
Jul 23 18:19:32 AdGuardHome[2944]: 2022/07/23 18:19:32.293124 [fatal] couldn't start forwarding DNS server: listening to udp socket: listen udp [IPV6]:53: bind: cannot assign requested address
````
Sounds like Adguard is trying to look for an IPV6 address, which won't work because I had to disable it on my box (french provider Orange)

**Comment by Viguro79** [comment]
I had to delete the line relative to ipv6 in `/var/www/adguardhome/AdGuardHome.yaml` in order to make Adguard home working again.
(second next line after the line `bind_hosts:`).
Maybe still an issue with the update process?

**Comment by Ddataa** [comment]
is this issue still valid ?

**Comment by Viguro79** [comment]
Not here at least

**Comment by Ddataa** [comment]
@addictif80 shall we close this issue ?

**Comment by OniriCorpe** [comment]
> Since my latest post, AdGuard Home work properly, but i don't know what i need to configure.
> And, on Youtube, many videos has blocked, with message "contact your network administrator"

To fix this:
Settings > General settings > Use safe search > Youtube (uncheck it)

**Comment by OniriCorpe** [comment]
I think we can close this issue, feel free to reopen it if needed ^w^
