### ISSUE TITLE
Adguard Home with VPNClient - Using the external IP and not accessible or usable from local network with local IP.

### ISSUE THREAD

**Issue by Optogram** [YunoHost-Apps/adguardhome_ynh#72]
### Description

*Adguard Home is using the VPN external IP and is accessible to everyone. Ithink that's the intended usage, but I'm self hosting Yunohost at home and wanted to use it locally. But the local IP adress doesn't respond and Adguard is telling me to use the external VPN IP adress to make it work.*

### Context

- Hardware: *Intel NUC with VPN*
- YunoHost version: 11.0.9.15
- I have access to my server: *Through everything*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
  - If yes, please explain:

### Steps to reproduce

- *Install the app*

### Logs

Since my Adguard won't start because of an other issue, I can't give more informations or screenshots.

**Comment by Optogram** [comment]
Hello, any news on that issue ?

**Comment by Optogram** [comment]
Hello, someone else came to me a few days ago with the same issue. Any news ?

**Comment by OniriCorpe** [comment]
hi!

replace your external IP with the local IP of your server in the config file:
`nano /var/www/adguardhome/AdGuardHome.yaml`

```
dns:
  bind_hosts:
    - 192.168.1.1
```

**Comment by Optogram** [comment]
It works !
Just to end this correctly, how do you find the local IPv6 adress to correct it as well ?
Thanks !

**Comment by OniriCorpe** [comment]
can I close this issue now? ^w^

**Comment by Optogram** [comment]
Yes, you can :)
