### ISSUE TITLE
Can't enable DNS over HTTPS because the port 443 is in use

### ISSUE THREAD

**Issue by enzonaute** [YunoHost-Apps/adguardhome_ynh#84]
## copy of the issue opened on 30 May, 2019 and which remains present to this day

present in v0.107.21

> ### Steps to reproduce
> 1. Install Adguard on a server that already has another Yunohost app installed
> 2. On the Settings menu, click on "Enable encryption"
> 3. (Optional) Copy your domain's certificate and private key to the corresponding fields
> 4. Click Save
> 
> ### Expected behavior
> The encryption should begin working, and DNS-over-HTTPS should start to be served from https://example.net/adguard/dns-query .
> 
> ### Actual behavior
> The site warns that the port 443 is already in use and disallows continuing the configuration. If a port other than 443 is used, the DNS-over-HTTPS functionality no longer works on certain devices (such as Android 9 Pie).
> 

<img width="1440" alt="port443-adguard" src="https://user-images.githubusercontent.com/72196495/210118893-b29c9058-486a-43eb-b822-fa0d1caedab4.png">

**Comment by syrabo** [comment]
Look: your-yunohost-admindomain.xxx/yunohost/admin/#/apps/adguardhome/config-panel/main

other: https://github.com/YunoHost-Apps/adguardhome_ynh/issues/3

**Comment by kay0u** [comment]
Can you explain why you want this configuration?

DOH works out of the box. You can use https://youradguarddomain.tld/dns-query or tls://youradguarddomain.tld

**Comment by enzonaute** [comment]
Sorry for that, I actually found the DOH option with
> Look: your-yunohost-admindomain.xxx/yunohost/admin/#/apps/adguardhome/config-panel/main

I was also able to modify the url of the corresponding api which was wrong.
Thanks for your help, I'm closing.

**Comment by luk6173** [comment]
Have same issue here, how I can solve it? My corresponding urls looks wrong for api and doh:

API Corresponding URL: https://re:adguard.mydomain.io/control
DOH Corresponding URL: https://re:adguard.prelovsky.io/dns-query

How to fix this?

Installed version: 0.107.43~ynh3
